---
- name: download calico yaml file
#  get_url: url="https://docs.projectcalico.org/v3.11/manifests/calico.yaml" dest=/tmp
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /tmp

#- name: edit calico yaml file
#  replace:
#    path: /tmp/calico.yaml
#    regexp: '# - name: CALICO_IPV4POOL_CIDR'
#    replace: '- name: CALICO_IPV4POOL_CIDR' 

#- name: edit calico yaml file
#  replace:
#    path: /tmp/calico.yaml
#    regexp: '#   value: "192.168.0.0/16"'
#    replace: '  value: "192.168.0.0/16"'
    
- name: edit calico yaml file
  replace:
    path: /tmp/calico.yaml
    regexp: '192.168.0.0/16'
    replace: '10.200.0.0/18'
    
- name: install calico
  shell: |
    kubectl apply -f /tmp/calico.yaml
  register: calico_result

- name: debug stdout
  debug:
    msg: "{{ calico_result.stdout }}"

- name: debug stderr
  debug:
    msg: "{{ calico_result.stderr }}"

