---
  - name: k8s netfilter
    sysctl:
      name: '{{ item }}'
      value: '1'
      reload: true
      sysctl_file: /etc/sysctl.d/k8s.conf
    with_items:
      - net.bridge.bridge-nf-call-iptables
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-ip6tables
