---
- name: add kubernetes repository
  yum_repository:
    file: kubernetes
    name: kubernetes
    description: kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    exclude: 'kube*'
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes

- name: install kubernetes package
  yum: 
    state: present
    enablerepo: kubernetes
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: 'kubernetes'


